# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Tester'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      environment:
        description: 'Environment (repository or production)'
        default: 'repository'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "log"
  log:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Job variable (environment variables scoped at the job level)
    env:
      JOB_VAR: ${{ vars.JOB_VARIABLE }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
    - name: Log secrets and variables
      # Step variables (environment variables scoped at the step level)
      env:
        APP_ID: ${{ vars.APP_ID }}
        API_KEY: ${{ secrets.API_KEY }}
        PROD_APP_ID: ${{ vars.PROD_APP_ID }}
        PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
      run: |
        echo "Environment: ${{ inputs.environment }}"
        echo "REPO_APP_ID: $APP_ID"
        echo "REPO_API_KEY: $API_KEY"
        echo "PROD_APP_ID: $PROD_APP_ID"
        echo "PROD_API_KEY: $PROD_API_KEY"
        echo "PROD_APP_ID: ${{ env.PROD_APP_ID }}"
        echo "PROD_API_KEY: ${{ env.PROD_API_KEY }}"
        echo "JOB_VAR: ${{ env.JOB_VAR }}"
